export const skills = {
  "Data Science": [
    "Python",
    "R",
    "SQL",
    "Tableau",
    "Power BI",
    "SAS",
    "SPSS",
    "Excel",
  ],
  "Deep Learning": [
    "Tensorflow",
    "Keras",
    "PyTorch",
    "OpenCV",
    "Pandas",
    "Numpy",
    "Scikit-learn",
  ],
  "UI/UX Designing": [
    "Figma",
    "Adobe XD",
    "Adobe Photoshop",
    "Adobe Illustrator",
    "Adobe InDesign",
    "Sketch",
    "Framer",
    "Mockplus",
  ],
  "Stock Market": [
    "Technical Analysis",
    "Fundamental Analysis",
    "Trading",
    "Investing",
    "Options",
    "Futures",
    "Forex",
  ],
  Business: [
    "Business Analysis",
    "Business Strategy",
    "Business Development",
    "Business Planning",
    "Business Management",
    "Business Consulting",
    "Business Intelligence",
  ],
  Health: [
    "Nutrition",
    "Fitness",
    "Weight Loss",
    "Weight Gain",
    "Muscle Gain",
    "Muscle Building",
    "Bodybuilding",
  ],
};
